version: '3.3'

services:
    db:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: ['3306:3306']
        environment:
            MYSQL_DATABASE: starterkit
            MYSQL_USER: starterkit
            MYSQL_PASSWORD: starterkit
            MYSQL_ROOT_PASSWORD: starterkit
    adminer:
        image: adminer
        restart: always
        ports: ['8888:8080']
    mailhog:
        image: mailhog/mailhog
        restart: always
        ports: ['1025:1025', '8025:8025']
volumes:
    minio:
